# Generated by Django 4.1.2 on 2023-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerform',
            name='desc',
            field=models.CharField(max_length=150),
        ),
    ]
