# Generated by Django 4.1.2 on 2023-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHome', '0002_alter_customerform_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerform',
            name='typ',
            field=models.CharField(default='mini-truck', max_length=20),
        ),
    ]
