# Generated by Django 4.1.2 on 2023-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHome', '0003_customerform_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerform',
            name='imag',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
