# Generated by Django 4.1.2 on 2023-03-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHome', '0004_customerform_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(default=None, upload_to=None)),
                ('dim1', models.IntegerField()),
                ('dim2', models.IntegerField()),
                ('typ', models.CharField(default='mini-truck', max_length=20)),
                ('loadWgt', models.IntegerField()),
                ('tadd', models.CharField(max_length=50)),
                ('fadd', models.CharField(max_length=50)),
                ('ddate', models.DateField()),
                ('budg', models.IntegerField()),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerForm',
        ),
    ]
